spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    kangmini: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

kangmini:
  a: aaa
  b: bbbbb
